name: Deploy to FTP server

on:
  push:
    branches:
      - main # Desplegar cuando haya un push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Desplegar al servidor FTP usando el cliente FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.1.0
        with:
          server: ${{ secrets.FTP_SERVIDOR }} # Usando el secreto FTP_SERVIDOR (server.ftpupload.net)
          username: ${{ secrets.username.b12_37391677 }} # Usando el secreto username.b12_37391677
          password: ${{ secrets.password.Jcg121299 }} # Usando el secreto password.asdasdas
          local-dir: ./build # El directorio local que quieres subir (ajústalo según tu caso)
          remote-dir: /public_html # El directorio remoto en tu servidor FTP
          dry-run: false # Si quieres probar antes de hacer el despliegue, ponlo como true
