name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Desplegar cada vez que haya un push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # (Opcional) Si tienes un proceso de construcción de tu sitio estático, aquí lo puedes añadir
      # Ejemplo si usas npm:
      - name: Build static site
        run: |
          npm install
          npm run build

      # Copiar los archivos generados a la raíz del repositorio
      - name: Copy files to root
        run: |
          cp -r ./build/* .  # Cambia ./build según el directorio donde se generen tus archivos estáticos
          # Asegúrate de copiar los archivos generados a la raíz del repositorio

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main  # Hacemos push a la rama main directamente
